######################################################################
# PixInsight Makefile Generator Script v1.144
# Copyright (C) 2009-2025 Pleiades Astrophoto
######################################################################
# Generated on .... 2025-04-07T08:57:47.464Z
# Project id ...... FITS
# Project type .... Module
# Platform ........ Linux/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

