######################################################################
# PixInsight Makefile Generator Script v1.144
# Copyright (C) 2009-2025 Pleiades Astrophoto
######################################################################
# Generated on .... 2025-04-07T08:57:47.530Z
# Project id ...... FITS
# Project type .... Module
# Platform ........ MacOSX/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

export PCLSRCDIR=/Users/jonathan/PCL/src
export PCLINCDIR=/Users/jonathan/PCL/include
export PCLLIBDIR64=/Users/jonathan/PCL/src/pcl/macosx/g++/arm64/Release
export DEVELOPER_ID="Developer ID Application: Mr Jonathan Kimmitt (Y53675G8V9)"

.PHONY: all
all: 
	$(MAKE) -f ./makefile-arm64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-arm64 --no-print-directory clean

