//     ____   ______ __
//    / __ \ / ____// /
//   / /_/ // /    / /
//  / ____// /___ / /___   PixInsight Class Library
// /_/     \____//_____/   PCL 2.9.4
// ----------------------------------------------------------------------------
// pcl/Timer.h - Released 2025-04-07T08:52:44Z
// ----------------------------------------------------------------------------
// This file is part of the PixInsight Class Library (PCL).
// PCL is a multiplatform C++ framework for development of PixInsight modules.
//
// Copyright (c) 2003-2025 Pleiades Astrophoto S.L. All Rights Reserved.
//
// Use of this source code is governed by the PixInsight Class Library License
// version 2.0, which can be found in the LICENSE file as well as at:
// https://pixinsight.com/license/PCL-License-2.0.html
// ----------------------------------------------------------------------------

#ifndef __PCL_Timer_h
#define __PCL_Timer_h

/// \file pcl/Timer.h

#ifndef __PCL_BUILDING_PIXINSIGHT_APPLICATION

#include <pcl/Defs.h>

#include <pcl/Control.h>

namespace pcl
{

// ----------------------------------------------------------------------------

/*!
 * \class Timer
 * \brief Client-side interface to a PixInsight %Timer object.
 *
 * A %Timer object can work in two ways:
 *
 * \li As a <em>periodic timer</em>, which generates a sequence of timer events
 * at regular time intervals.
 *
 * \li As a <em>single-shot timer</em>, which generates a single timer event
 * after a prescribed time interval.
 *
 * ### TODO: Write a detailed description for %Timer.
 */
class PCL_CLASS Timer : public UIObject
{
public:

   /*!
    * Default constructor.
    */
   Timer();

   /*!
    * Destroys a %Timer object.
    */
   ~Timer() override
   {
   }

   /*!
    * Ensures that the server-side object managed by this instance is uniquely
    * referenced.
    *
    * Since timers are unique objects by definition, calling this member
    * function has no effect.
    */
   void EnsureUnique() override
   {
      // Timers are unique objects by definition
   }

   /*!
    * Returns a reference to a null %Timer instance. A null %Timer does not
    * correspond to an existing timer in the PixInsight core application.
    */
   static Timer& Null();

   /*!
    * Returns the timer interval in seconds.
    */
   double Interval() const;

   /*!
    * Sets the timer interval in seconds.
    */
   void SetInterval( double seconds );

   /*!
    * Returns true iff this is a single-shot timer.
    */
   bool IsSingleShot() const;

   /*!
    * Returns true iff this is a periodic timer.
    *
    * This is a convenience member function, equivalent to
    * !IsSingleShot()
    */
   bool IsPeriodic() const
   {
      return !IsSingleShot();
   }

   /*!
    * Enables or disables single-shot mode for this %Timer object.
    */
   void SetSingleShot( bool = true );

   /*!
    * Enables or disables periodic mode for this %Timer object.
    */
   void SetPeriodic( bool p = true )
   {
      SetSingleShot( !p );
   }

   /*!
    * Returns true iff this %Timer object is active. An active timer is
    * generating timer events.
    */
   bool IsRunning() const;

   /*!
    * Activates this %Timer object. Starts generation of timer event(s).
    */
   void Start();

   /*!
    * Stops this %Timer object, if it is currently active.
    */
   void Stop();

   /*!
    * Returns the number of timer events generated after the last call to
    * Start().
    */
   unsigned Count() const
   {
      return count;
   }

   // -------------------------------------------------------------------------
   // Event handlers
   //
   // void OnTimer( Timer& sender );

   /*!
    * \defgroup timer_event_handlers Timer Event Handlers
    */

   /*!
    * Defines the prototype of a <em>timer event handler</em>.
    *
    * A timer event is generated by an active %Timer object, either at regular
    * intervals (periodic timer), or just once when the timer period elapses
    * (single-shot timer).
    *
    * \param sender  The control that sends a timer event.
    *
    * \ingroup timer_event_handlers
    */
   using timer_event_handler = void (Control::*)( Timer& sender );

   /*!
    * Sets the timer event handler for this %Timer object.
    *
    * \param handler    The timer event handler. Must be a member function of
    *                   the receiver object's class.
    *
    * \param receiver   The control that will receive timer events from this
    *                   %Timer.
    *
    * \ingroup timer_event_handlers
    */
   void OnTimer( timer_event_handler handler, Control& receiver );

private:

   timer_event_handler onTimer = nullptr;
   unsigned            count = 0;

   Timer( void* h ) : UIObject( h )
   {
   }

   void* CloneHandle() const override;

   friend class TimerEventDispatcher;
};

// ----------------------------------------------------------------------------

} // pcl

#endif   // __PCL_BUILDING_PIXINSIGHT_APPLICATION

#endif   // __PCL_Timer_h

// ----------------------------------------------------------------------------
// EOF pcl/Timer.h - Released 2025-04-07T08:52:44Z
