######################################################################
# PixInsight Makefile Generator Script v1.144
# Copyright (C) 2009-2025 Pleiades Astrophoto
######################################################################
# Generated on .... 2025-04-07T08:58:07.630Z
# Project id ...... installer
# Project type .... X11Installer
# Platform ........ FreeBSD/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

